# Generated by Django 3.0.7 on 2020-07-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blog', '0004_remove_blogpage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageRevision',
            fields=[
                ('pagerevision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.PageRevision')),
            ],
            bases=('wagtailcore.pagerevision',),
        ),
    ]
