# Generated by Django 3.0.5 on 2020-06-17 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default-sb.jpg', upload_to='surfboard_pics')),
                ('notes', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('length', models.FloatField(help_text="Enter in 'cm's", max_length=5)),
                ('width', models.FloatField(help_text="Enter in 'cm's", max_length=5)),
                ('thickness', models.FloatField(default=5, help_text="Enter in 'cm's", max_length=5)),
                ('volume', models.FloatField(blank=True, help_text="Enter in 'millilitres's.  A calculation will be made for you if you fill in L x W x T", max_length=5, null=True)),
                ('wave_range_start', models.FloatField(blank=True, help_text="Enter in 'cm's", max_length=5, null=True)),
                ('wave_range_end', models.FloatField(blank=True, help_text="Enter in 'cm's", max_length=5, null=True)),
                ('make', models.CharField(max_length=100)),
                ('shaper', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
